"""UI 抽象层。

以后要换 Qt/QML 大图界面，只需要再写一个实现了同一套方法的类，
Hub 其余部分（app/session）完全不用动。
"""
from __future__ import annotations

from typing import Protocol


class HubUI(Protocol):
    def set_games(self, games: list[tuple[str, str]]) -> None: ...
    def set_status(self, text: str) -> None: ...
    def hide(self) -> None: ...
    def show(self) -> None: ...
    def refresh(self) -> None: ...
    def run(self) -> None: ...
    def destroy(self) -> None: ...
